# Site Settings
title: Robert Shade's Resume
url: 'https://robert-shade.github.io'
baseurl: '' #change it according to your repository name

# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
style: styles-6

#Profile information
name: Robert Shade
tagline: Developer/Technologist
pic: profile.jpg  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
summary: 'Technical leader with broad experience. Passionate about creating innovative, secure, and valuable software
solutions. Always eager to take on new challenges and opportunities to expand my skillset.'
pdf: assets/robert_shade.pdf

#sidebar links
email: robert.shade@gmail.com
website: robert-shade.github.io #do not add http://
linkedin: robertshade
github: robert-shade
twitter: '@rshade'
#Update all the sections by editing the files inside _data folder.

# Tracker
analytics: UA-111940204j-1

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
